username: **********
password: **********

positions:
  - Software Engineer
  - Mid Software Developer
  - Mid Level DevOps Engineer
  - Python Developer

locations:
  - Istanbul
  - Amsterdam
  - Berlin

# --------- Optional Parameters -------
uploads:
  Resume: /home/deniz/codes/deniz-gokcin-cv/deniz-gokcin-cv.pdf
  #Cover Letter: /Users/aliasgarmerchant/Desktop/LinkedIn-Easy-Apply-Bot/Cover_G.docx
  #City: Jersey City, New Jersey, United States
#  Photo: # PATH TO photo


output_filename: output.csv

# blacklist:
# - # Company names you want to ignore
